version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gifts-client
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-3000}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3000}
    ports:
      - '${CLIENT_PORT:-3001}:3000'
    networks:
      - gifts-network

networks:
  gifts-network:
    driver: bridge

