services:
  postgres:
    image: postgres:16-alpine
    container_name: gifts-postgres
    restart: unless-stopped
    env_file:
      - ./server/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U "$POSTGRES_USER" || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - gifts-network

  redis:
    image: redis:7-alpine
    container_name: gifts-redis
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gifts-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: gifts-server
    restart: unless-stopped
    env_file:
      - ./server/.env
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - gifts-network
    volumes:
      - ./server/libs/infrustructure/prisma:/app/libs/infrustructure/prisma
      - ./server/libs/statics:/app/libs/statics

  nftbuyber:
    build:
      context: ./nftbuyber
      dockerfile: Dockerfile
    container_name: gifts-nftbuyber
    restart: unless-stopped
    env_file:
      - ./server/.env
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${NFTBUYBER_PORT:-3334}
      TONCENTER_URL: ${TONCENTER_URL}
      TONCENTER_API_KEY: ${TONCENTER_API_KEY}
      TON_API_URL: ${TON_API_URL}
      TON_API_KEY: ${TON_API_KEY}
      MARKETPLACE_API_KEY: ${MARKETPLACE_API_KEY}
      WALLET_MNEMONIC: ${WALLET_MNEMONIC}
      REDIS_URL: redis://redis:6379
      GETGEMS_API_KEY: ${GETGEMS_API_KEY}
    ports:
      - '${NFTBUYBER_PORT:-3001}:3001'
    networks:
      - gifts-network
    depends_on:
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:

networks:
  gifts-network:
    driver: bridge

